version: '3'
services:
  workflowdb:
    image: postgres:13
    container_name: workflowdb
    volumes:
      - ./init_db_dev.sh:/docker-entrypoint-initdb.d/init.sh
      - workflowdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      default:
        aliases:
          - workflowdb
#  workflowdbtest:
#    image: postgres:13
#    container_name: workflowdbtest
#    volumes:
#      - ./init_db_devtest.sh:/docker-entrypoint-initdb.d/init.sh
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_PASSWORD: postgres
#    networks:
#      default:
#        aliases:
#          - workflowdbtest
#
#  jupyter-almond:
#    image: almondsh/almond:0.10.9
#    container_name: jupyter-almond
#    ports:
#      - "8888:8888"
#    volumes:
#      - ./notebooks/:/home/jovyan/notebooks
#      - ./target/scala-2.13/masterthesis-khipu-assembly-0.1.jar:/home/jovyan/jar/masterthesis-khipu-assembly-0.1.jar
#    working_dir: /home/jovyan/

volumes:
  workflowdb:

networks:
  default: