@startuml
actor "User" as USER
database "PostgreSQL" as DB
node "Web application" as CLIENT
node "Server" as SERVER {
    rectangle "Rest API" as API
    collections "Constraint solver engine" as INTELLIGENCE
    rectangle "Business logic" as LOGIC
}

LOGIC -left-> DB : "data"
API <-down- CLIENT: "HTTP Request"
API -down-> CLIENT: "HTTP Response"
LOGIC <-down- API
LOGIC -right-> INTELLIGENCE
USER -right-> CLIENT
@enduml